server:
  port: 9091


rabbit:
  group: 1

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://132.232.14.40:3309/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 132.232.14.40
    port: 5672
    username: test
    password: password
  redis:
    port: 6379
    database: ${rabbit.group}
    password: foobared
    timeout: 1000
    jedis:
      pool:
        max-idle: 8
        max-wait: -1
    host: 132.232.14.40
  main:
    allow-bean-definition-overriding: false

mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.rabbitconsumer.demo.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug


