server:
  port: 8080

spring:
  datasource:
    username: root
    password: password
    url: jdbc:mysql://localhost:3309/test?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin

mybatis:
  mapper-locations: classpath:mybatis/*/*.xml
  type-aliases-package: com.rabbitprovider.demo.pojo

#showSql
logging:
  level:
    com:
      example:
        mapper : debug
